custom:
  message: hiParth
spring:
 application:
    name: config-client1
 datasource:
    password:
    url: jdbc:h2:file:C:/h2data/sample
    username: sa
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
